- name: creating container config
  hosts: rhel9
  gather_facts: false
  tasks:
   - name: creating container
     containers.podman.podman_container:
       name: Workshop
       image: registry.redhat.io/rhel8/httpd-24
       state: started
       publish:
        - '8088:80'
